# Dockerfile para backend Node.js
FROM node:18-alpine
WORKDIR /app
COPY backend/package*.json ./
RUN npm ci --production && npm install --save-dev sequelize-cli
COPY backend/. .
# Garante que scripts do src/scripts estejam disponíveis
COPY backend/src/scripts ./src/scripts
EXPOSE 3001
CMD ["npm", "run", "start:migrate"] 