version: '3.9'
services:
  db:
    image: postgres:15
    container_name: finance-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: finance123
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: finance-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: finance
      DB_PASSWORD: finance123
      DB_NAME: finance
      # Adicione outras variáveis conforme necessário
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: finance-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data: 